go:
  application:
    cache-tpl: false # 默认不缓存模板,省内存，方便开发
  log:
    level: error        # debug info warn error
    output: stdout,file # stdout：只写控制台，file:只写文件，默认：双写
  cache: ram # redis ram
#  redis:
#    host: ${REDIS_HOST:192.168.81.228}
#    port: ${REDIS_PORT:6379}
#    password: ${REDIS_PWD:123456}
  datasource:
    show-sql: true   # 打印SQL到日志
    auto-migrate: update # update/none 同步表结构，见 init.go
    driver: sqlite3
    master: data.db
    # driver: mysql
    # master: ${MYSQL_MASTER:"root:qwer1234@tcp(192.168.81.228:3306)/test?charset=utf8"}
    slave: ""

 #代理转发
#  proxy:
#    enable: true
#    prefix:
#      - /video=192.168.100.110
#      - /lostvip=lostvip.com
#代码生成器配置
gen:
  author: lv
  #大模块，如lv_framework、main、demo
  moduleName: main
  #小模块，业务包
  packageName: mywork
  #覆盖旧的代码
  overwrite: true
  #新生成的菜单挂到哪个菜单下
  parent_menu_id: 4