go:
  application:
    debug: true
  log:
    output: stdout #生产环境要注释，不会记录到文件
  redis:
#    host: ${"REDIS_HOST":"127.0.0.1"}
    host: ${"REDIS_HOST":"robnote.com"}
    port: ${"REDIS_PORT":6379}
    password: ${"REDIS_PWD":"Ssz123!"}
  datasource:
    #    driver: sqlite3
    #    master: data.db
    driver: mysql
    #master: "root:qwer1234@tcp(127.0.0.1:3307)/ruoyi-go?charset=utf8"
    #master: ${MYSQL_MASTER:"root:qwer1234@tcp(127.0.0.1:3307)/ruoyi-go?charset=utf8"}
    master: ${MYSQL_MASTER:"root:Ssz123!@tcp(robnote.com:13306)/ruoyi-go?charset=utf8"}
    slave: ""

gen:
  author: "lv"
  moduleName: "biz"
  packageName: "robvi"
  autoRemovePre: true