version: '3.3'    
services:
  sys:
    image: reg.lostvip.com/sys:1.2.0
    ports: 
      - "3001:3001"
    volumes:
      - /mnt/nfs/ry/public/upload:/root/public/upload
    deploy:
      replicas: 2
      restart_policy:  
        condition: on-failure
